baseURL: https://brentglowinski.com
languageCode: en-us
title: brent has a website

theme: ["PaperMod"]
paginate: 5

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: About
          url: about/
          weight: 20


params:
  homeInfoParams:
    Title: hello
    Content: this is one of the sites of all time
  socialIcons:
    - name: "mastodon"
      url: "https://mastodon.social/@brenticus"
    - name: "github"
      url: "https://github.com/BrenTicus"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/brent-glowinski-b547748b/"
    - name: "storygraph"
      url: "https://app.thestorygraph.com/profile/brenticus"
    - name: "rss"
      url: "index.xml"
  ShowAllPagesInArchive: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
